name: Compile Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Compile
        run: |
            npm install
            npm run compile
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "# [INSTALLATION INSTRUCTIONS HERE!!!](https://github.com/LITdevs/SaladBind#Installation)"
          token: ${{ secrets.BEEPBOOP_TOKEN }}
          files: |
            bin/saladbind-win.exe
            bin/saladbind-macos
            bin/saladbind-linux
